### ISSUE TITLE
for Markdown parsing

### ISSUE THREAD

**Issue by lg0** [ruhoh/ruhoh.rb#1]
there are some problems when maruku parsing my post.
how can i use Kramdown for markdown parsing？

anyway thank you for your great work, its pretty easy to use.

**Comment by rriemann** [comment]
this project looks really interesting, but please take advantage of using kramdown. It's more than 4x faster. ;)
http://kramdown.rubyforge.org/index.html

**Comment by plusjade** [comment]
@saLOUt thank you I will try it out as I have been experiencing issues with Maruku myself.

**Comment by plusjade** [comment]
@saLOUt it looks like GitHub uses RedCarpet for their internal Markdown stuff? What are your views on it: https://github.com/tanoku/redcarpet ??

**Comment by cboettig** [comment]
I've taken to redcarpet2 -- [Github seems to have only the 1.17.2](http://stackoverflow.com/questions/8395347/gollum-wiki-undefined-method-new-for-redcarpetmodule) supported on their Jekyll engine, not sure what version they are using to power Github Flavored Markdown.  

I've been using redcarpet 2 because it allows `fenced code blocks`, `tables`, and `no_intra_emphasis`. I refuse to write markdown files that need non-markdown highlighting syntax like `{% highlight %}` All in all I've enjoyed redcarpet2 (not gh-pages compatible, but that's not an issue for ruhoh ;-)   I then use a bit of CSS to have solarized colors for syntax highlighting.  

I imagine it's valuable to be able to set the markdown parser in `_config.yml`, along with options, just as Jekyll does, since everyone will have different favorites.   Is that possible in ruhoh?

**Comment by rriemann** [comment]
I always use kramdown for my projects – it is at least supported by gh-pages.

**Comment by plusjade** [comment]
@cboettig I agree about wrapping code in liquid tags; feels quite nasty to me. Anything that is encapsulating might as well regress back to HTML!

I'm going to lean toward RedCarpet as the default since it also supports native table of contents generation, but I will provide  the ability to swap out parsers. Although I don't think I'll do it as a config setting because the result is a little too convoluted to me: https://github.com/mojombo/jekyll/blob/master/lib/jekyll/converters/markdown.rb. I'm sure GitHub does it this way in order to support multiple settings on their environment, so it needs to be locked down.

If I do it as a plugin, it becomes much more robust in that you can set it up exactly how u want it using any ruby code you want, and you won't have to use a go-between to provide configuration settings. Something like:

``` ruby
require 'kramdown'

Blah < Ruhoh::Plugin

  converter :custom_converter
  extensions ['.md', '.markdown']

  def custom_converter(page)
    # Get crazy with customizations here, just make sure to output the converted string
    Kramdown::Document.new(page.content).to_html
  end

end
```

This will probably not resemble anything like the actual implementation, it's for illustration purposes only, but you get the point!

Being that I'm so obsessed with my "ruhoh is modular" vision, I try to take a module swapping/override approach rather than module configuration. What do you guys think?

**Comment by cboettig** [comment]
Word.

I agree that the modular approach you describe sounds more sensible than
the hardwired configuration file.

On Thu, May 10, 2012 at 1:18 PM, Jade <
reply@reply.github.com

> wrote:
> 
> @cboettig I agree about wrapping code in liquid tags; feels quite nasty to
> me. Anything that is encapsulating might as well regress back to HTML!
> 
> I'm going to lean toward RedCarpet as the default since it also supports
> native table of contents generation, but I will provide  the ability to
> swap out parsers. Although I don't think I'll do it as a config setting
> because the result is a little too convoluted to me:
> https://github.com/mojombo/jekyll/blob/master/lib/jekyll/converters/markdown.rb.
> I'm sure GitHub does it this way in order to support multiple settings on
> their environment, so it needs to be locked down.
> 
> If I do it as a plugin, it becomes much more robust in that you can set it
> up exactly how u want it using any ruby code you want, and you won't have
> to use a go-between to provide configuration settings. Something like:
> 
> ``` ruby
> require 'kramdown'
> 
> Blah < Ruhoh::Plugin
> 
>  converter :custom_converter
>  extensions ['.md', '.markdown']
> 
>  def custom_converter(page)
>    # Get crazy with customizations here, just make sure to output the
> converted string
>    Kramdown::Document.new(page.content).to_html
>  end
> 
> end
> ```
> 
> This will probably not resemble anything like the actual implementation,
> it's for illustration purposes only, but you get the point!
> 
> Being that I'm so obsessed with my "ruhoh is modular" vision, I try to
> take a module swapping/override approach rather than module configuration.
> What do you guys think?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ruhoh/ruhoh.rb/issues/1#issuecomment-5635467

## 

Carl Boettiger
UC Davis
http://www.carlboettiger.info/

**Comment by plusjade** [comment]
@CrazyApi @saLOUt @cboettig version 0.3.0 now supports plugins, which can be used to re-implement the markdown converter.

http://ruhoh.com/blog/releases/version-030/

Please see specifically: http://ruhoh.com/usage/plugins/#toc_4

Thanks for all your guys' feedback. I went with redcarpet as the default because of the fenced-code-block support, but switching to kramdown is now very easy.
