### ISSUE TITLE
feature - ignore files ending in ~

### ISSUE THREAD

**Issue by floer32** [ruhoh/ruhoh.rb#102]
Text editors like gedit save back up files whose extensions end in ~ (like .md~). It is common to set up a .gitignore for these. By doing this, these duplicate posts won't make it to the real blog.

But I wonder, is it easy enough to make ruhoh ignore these when serving the development version of the site? I'm new to Ruby (coming from Python) so I don't know if this is more an issue with rackup or what. For now I've just turned off the backup in gedit, but I figured I'd post this here as it is a bit jarring when you're first starting with ruhoh. Takes a second to realize why you're seeing two of every post.

Thank you for all of your work, this is a really excellent thing.

**Comment by plusjade** [comment]
You can use the `posts["exclude"]` and `pages["exclude"]` configuration settings as outlined here: http://ruhoh.com/usage/configure/#toc_14

In your case:

```
posts:
  exclude: "~$"

pages:
  exclude: "~$"

```

One user had this exact same issue and this was added specifically for this use case! Let me know how it goes.

**Comment by floer32** [comment]
smh Of course! Should have read more of the docs.

**Comment by waynedpj** [comment]
i am currently seeing this same problem with layouts in my theme directory with ruhoh 2.6, even with various attempts to exclude Emac's ~ backup files in my config.yml, including:

```
"themes/demonstrated":
  use: theme
  exclude: "~$"
```

it actually causes all kinds of weird/hard-to-track problems when ruhoh pulls in the ~ file before/instead of the current file (see my problems in #254 ).
i know i could disable these files being generated in Emacs, but they can be useful as quick/simple backups.  so perhaps a way to set the exclude glob globally in `config.yml` is needed?

thanks, w
