### ISSUE TITLE
RSS generates full-page code instead of just content

### ISSUE THREAD

**Issue by themindfulbit** [ruhoh/ruhoh.rb#103]
If you leave the description field blank on a post, the existing RSS feed generator renders the entire page, including the header, footer and sidebar. This can be distracting, and it's common for blog RSS feeds to only include the bare content for each post.

The code that governs this behavior is found in the file `/lib/ruhoh/compilers/rss.rb` on line 29:

``` ruby
xml.description_ (post['description'] ? post['description'] : page.render)
```

With a slight change, the RSS feed will render only the post content, which offers much cleaner output:

``` ruby
xml.description_ (post['description'] ? post['description'] : Ruhoh::Converter::Markdown.convert(page.content))
```

Unfortunately my revised snippet won't process mustache tags in its current form. This is an issue with embedded image links if `{{urls.media}}` is used. 

I'm not sure what needs to be tweaked to get the mustache working, but someone with better knowledge of the codebase may have better luck.

**Comment by plusjade** [comment]
Ah yes, this problem was addressed and fixed in [this commit](https://github.com/ruhoh/ruhoh.rb/commit/9dd7c146d8fd9b65aacb74a4c798ae5a6bc41064). Issue #86 discusses the solution. 

Unfortunately I have not bumped the gem version in some time =/ as I'm working on ruhoh 2.0. You might try bundling the gem from github which will give you the most recent changes:

``` ruby
gem 'ruhoh', :git => "git@github.com:ruhoh/ruhoh.rb.git"
```

Let me know if this helps!

**Comment by themindfulbit** [comment]
Works perfectly, sorry I missed the earlier issue.

The new code solved everything (including the mustache problem) and is far more elegant.

Thanks!
