### ISSUE TITLE
Contents of /media should be copied to /compiled/assets/media with version 2.x like it did with 1.x

### ISSUE THREAD

**Issue by webmasterkai** [ruhoh/ruhoh.rb#121]
Thanks for the update! It's really exciting.

When I do a clean install, add a file to /media and run compile it doesn't seem to copy over.

```
$ cd media
$ wget -O plusjade.jpg http://secure.gravatar.com/avatar/b835c3656fab4a9241d6b7f983d6fce3?s=400
$ cd ../
$ bundle exec ruhoh compile
$ ls compiled/assets/media
ls: compiled/assets/media: No such file or directory
```

I wish I knew ruby so I could try and figure it out.

**Comment by plusjade** [comment]
@webmasterkai thanks man! Oversight on my part: https://github.com/ruhoh/ruhoh.rb/commit/db4cdbda8608bb7dbb108cb52cbc91324e15dec8

To update, I think you just delete `Gemfile.lock` then run `bundle install` again. (The reason is I am not updating the version number on every change so bundler will assume the version is current and not re-download the HEAD from github)

Please try your test again and verify it works, thanks!

**Comment by webmasterkai** [comment]
You are awesome! Works perfectly.

Thanks for all of your work on Ruhoh. It's my favorite.

For the record this was my process of updating. It worked just like you suggested.
From the website root:
    $ rm Gemfile.lock
    $ bundle install
    $ rm -rf compiled/*
    $ bundle exec ruhoh compile
    $ ls compiled/assets/media
    all.png of.jpg my assets.pdf

**Comment by plusjade** [comment]
@webmasterkai just glad you use it!  Thank you for contributing.
