### ISSUE TITLE
Could not update Git repository by ruhoh.com

### ISSUE THREAD

**Issue by zx1986** [ruhoh/ruhoh.rb#13]
hello!

last night I built my first ruhoh blog powered by ruhoh.com,
I follow the steps on the home page of ruhoh.com, and it works fine.

but I after did:
ruhoh theme twitter
git add .
git commit -a 
git push

I got:
2012-04-18 16:02:28 UTC
ERROR: Could not update Git repository

I could not fix it.
then, I remove my git repository on Github.com, and create a new one with the same name.

I got :
2012-04-18 16:22:06 UTC
SUCCESS: Blog compiled and deployed.

but, again, after I did a commit push.
I got:
2012-04-18 16:40:12 UTC
ERROR: Could not update Git repository

I checkout the repository in another PC now,
and I did a commit push again to Github.com,

but I got nothing update on zx1986.ruhoh.com.

here is my log:
http://zx1986.ruhoh.com/log.txt

here is my blog:
http://zx1986.ruhoh.com/
http://zx1986@github.com/zx1986/zx1986.ruhoh.com.git

thanks! :-)

I am a Octopress user in Taiwan,
I like what Jekyll and Octopress did,
when I knew there is ruhoh, I mean ... WOW! WOW! WOW!

you did a great job, Jade!

**Comment by plusjade** [comment]
@zx1986  Hey man, I'm an ass. It's been a month since I even bothered to reply. All I can say is I was having multiple problems with the post.ruhoh.com hook so couldn't really tell you what was the problem =(

But! if you are still there, I have fixed all the (known) issues and am happy to report your blog is up and running: http://zx1986.ruhoh.com/  I just tested a POST hook and all is well. 

Thanks for your support and I definitely appreciate the vote of confidence.

**Comment by zx1986** [comment]
hello, Jade!
I'm back. sorry for take so long time.

I got blogspot, octopress, ruhoh run with my blog.
the ruhoh is my favorite, really :-)
it's simple and graceful.

but I got a little bit issue here:
http://zx1986.ruhoh.com/log.txt

![compiled fail](http://i.imgur.com/1D9d2.png)

and I fix my site.yml like this, it works:

![compiled ok](http://i.imgur.com/RbCqS.png)

anyway, my ruhoh blog works fine now, just a little issue that I couldn't figure out, and I want to tell you.
maybe this is a UTF8 issue ?

THANKS YOU SO MUCH AGAIN FOR CREATING ruhoh!
