### ISSUE TITLE
compiling becomes crazy slow

### ISSUE THREAD

**Issue by coolaj86** [ruhoh/ruhoh.rb#132]
Once you import more than a few dozen articles from your old blog, compiling becomes wicked slow.

It seems that having a `./caches` and `./compiled` and changing the logic so that if a post hasn't changed it gets copied instead of recompiled would make sense.

Good idea? Bad idea?

**Comment by plusjade** [comment]
Great idea! 

### Internal Caching

Generic object caching is easy enough to do it just hasn't been implemented. It should give a significant boost to the compile task. Basically, whenever you reference any kind of resource from `ruhoh.db.` it gives you a fresh version for the sake of previewing it. However in compile mode it should generate the resource only once and serve a cached version for any subsequent call to that same resource. I'm pretty sure I broke this in getting previewing to work. Now it's just a matter of adding back the cache when env == 'production'

### Page-level Caching.

Also a good idea, though it would take some time to implement, and it would probably get complicated to truly work. For example if you have a global navbar and you change it, it invalidates every page even though the page content itself didn't change. Any 'dynamic' logic you use in your pages will be victim to this issue. If you list data from another resource, the page would have to know when any piece of data it is including has been changed in order to invalid its cache =/.

I'm hoping internal caching mechanism will be good enough for the couple hundred posts use-case. I'll update this issue when it is in!

**Comment by coolaj86** [comment]
Thanks!

For the page-level caching it does make sense that if the layout the page changes that everything needs to be recompiled. However I think it would be fair to say that if you want to do crazy stuff with templates inside of a post you should pass a --no-cache option.

**Comment by plusjade** [comment]
You wouldn't need to do anything _inside_ of a post for the rendered post-page to be invalidated. Drawing on the navigation example again, if I want to add an extra global navigation link inside of `default.html`, say my new twitter handle, well any post/page that uses that template needs to be updated. Point being it's kind of a never ending game of when to invalidate the cache.
