### ISSUE TITLE
how to access page.xyz in /themes/twitter/layouts/paginator.html?

### ISSUE THREAD

**Issue by coolaj86** [ruhoh/ruhoh.rb#136]
If I have

```

---
...
screencast: true

---
```

Then I want to be able to put an image by the title in the pagination, however, it isn't clear to me how to do this. I've tried `{{# page.screencast }}...` and `{{#screencast }}...`, but neither seem to work. I grepped around the code a bit, but didn't find an answer...

what the `with` is going on here? `{{title}}`, `{{date}}`, etc with no `page.` prefix

**Comment by plusjade** [comment]
The paginated pages being rendered using paginator.html do not exist. Each is injected dynamically with an iterated page number in order create pages 1-n. Here's the logic: https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/resources/paginator/previewer.rb#L12-15

The YAML data, where exactly is it? Is it in the paginator.html file? If so paginator.html is a sub-layout of which there is currently no support for accessing its meta-data (I can implement it though).  

I'm not sure I understand the use-case though, is the image going to be rendered within the master template (default.html) or within paginator.html? I'm omitting saying "on the page" because there is no actual page as I've mentioned. If  the latter, couldn't you hardcode it right into paginator.html? If the former, then I think I may understand but not sure.

**Comment by coolaj86** [comment]
A few hours ago if you had visited http://blog.coolaj86.com you would have seen big bulky youtube videos taking up tons of real-estate for each post.

I just moved the showing the video logic into the post.html template so that the videos only show up when you access a post directly, such as http://blog.coolaj86.com/articles/migrate-from-blogger-to-ruhoh-with-proper-redirects.html

I still want the paginated summaries to show whether or not there's a video associated with the post so that if someone lands on the homepage rather than by google search that they will get the hint that these posts have videos.

This is the snippet I'm trying to put into paginator.html:

```
{{# youtube }}<img src="{{urls.base_url}}/media/screencast.png" />{{/ youtube }}
```

does that make sense?

**Comment by plusjade** [comment]
Yep, makes sense. Your code is correct as seen here: https://github.com/coolaj86/blog.coolaj86.com/commit/c773a554cc858a69e244764193ec4d634ade998a

However the default blog actually uses "/' as the first page of the paginator (like a traditional old school blog). So if you look at index.html you'll see more paginator code: https://github.com/coolaj86/blog.coolaj86.com/blob/master/pages/index.html#L8-18

Add the changes from the first file to the index as well and it should work! Also, of course, remember to set `youtube: true` for posts that have videos.

**Comment by coolaj86** [comment]
Ah, in my late-nightedness I missed a nuance. Thank you!

All is well!
