### ISSUE TITLE
ruhoh 2.0 significantly slower to compile?

### ISSUE THREAD

**Issue by tlupfer** [ruhoh/ruhoh.rb#137]
I've been noticing this for a while, but assumed it was something specific to my setup. However, I've reproduced it with different content, themes and machines. It is not really noticeable until the number of pages/posts is over 50 or thereabouts.

Compiling the same 230 posts/pages:

Ruhoh 1.1
real    0m5.964s
user    0m5.733s
sys 0m0.200s

Ruhoh 2.0
real    2m37.668s
user    2m35.952s
sys 0m1.046s

Thoughts on why this might be happening?

**Comment by plusjade** [comment]
@tlupfer thanks for the report. ruhoh 2.0 has significantly more overhead in terms of spawning new objects so it is going to take a performance hit compared to 1.1. However what's happening now is ruhoh is _not_ caching any of the objects so its creating them new every time they are needed. This is helpful when in preview mode because you'll always see the most updated data. However you don't want that in compile mode. I just need to turn caching on when compiling and we should see a performance increase.  This is something  I haven't gotten to but I'll treat this ticket as a bug for me to fix.

P.S. You can see the hints from the compile output. You might see 'n/n posts processed' multiple times which means they are being processed multiple times!

**Comment by tlupfer** [comment]
@plusjade Version 2.1 is significantly slower than 2.0. To compile ~280 posts took 26 minutes. However, it seems entirely due to page.next and page.previous. Removing that section from the post layout results in a compile time of about 3 minutes. Weird or expected?

**Comment by plusjade** [comment]
Well it's definitely a bug since 26 minutes to compile anything is quite unreasonable. 

I've added a "smart" caching strategy while trying hard to avoid complexity. I'm pretty we just need to catch scenarios in which the cache isn't being handled correctly or the method call is not taking advantage of the cache. 

Very likely the case with page.next/page.previous as  I see 3 high-level calls that result in scanning of the entire collection(s). Note scanning the entire collection should be _normal_ in order to serve the latest data, but when in compile mode these calls should be intercepted by the cache and return data without actually processing anything.

Is there any way I can test out your specific blog repository, I didn't see the source available on your github profile. I'd like to do some benchmarking with that and fix the slow running methods.

**Comment by tlupfer** [comment]
It's now up at tlupfer/www.slowtheory.com.git

**Comment by plusjade** [comment]
Great thanks ill check it out right now

**Comment by plusjade** [comment]
@tlupfer good news is by adding a cache conditional to `collection.all` I've got compile time for your blog down to 26 seconds. Basically it takes time to [filter the collection Array](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/resources/pages/collection_view.rb#L11-15) on every call so we'll cache the filtered result when in compile mode.

Though now I see custom permalink formats are completely messed up, so I'll fix that and push updates all together.

Thanks for hinting at page.prev/page.next !

EDIT: updated code link to more relevant code reference

**Comment by plusjade** [comment]
Here's the pending fix:

Replace https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/resources/pages/collection_view.rb#L11-15 with:

``` ruby
    def all
      ruhoh.cache.get("#{ resource_name }_all") ||
        ruhoh.cache.set("#{ resource_name }_all", dictionary.each_value.find_all { |model|
              File.basename(File.dirname(model.id)) != "drafts"
            }.sort
          )
    end
```

Haven't merged this in because I need to invalidate this cache on every request-cycle and need to test to make sure it works, but need to go to sleep now!

This should get your compile time down to 27-29 seconds.

**Comment by tlupfer** [comment]
Much better!
