### ISSUE TITLE
RSS Feed Generation

### ISSUE THREAD

**Issue by davejlong** [ruhoh/ruhoh.rb#14]
When compiling the site into static files, an RSS/Atom feed should be generated for the posts. When the site is compiled with `ruhoh compile` or published to ruhoh.com hosting (which I am assuming uses `ruhoh compile`) the posts should be looped through to generate the item tags. Any other settings for the RSS feed (title, description, etc.) can just be taken from the YAML config files.

**Comment by davejlong** [comment]
I've started working on an RSS Builder gem at github.com/davejlong/rss-builder and once I finish it I will try to fold it into a ruhoh fork, but I wanted to post an issue here in case there already is a way to generate the feed and I couldn't find it.

**Comment by plusjade** [comment]
@davejlong no there has been no development in the RSS stuff for ruhoh. I would greatly appreciate your help in that. A few people have contributed some basic atom feed generators in Jekyll-Bootstrap, so I had just planned to port them over to ruhoh. However I honestly don't understand how RSS works because I don't use RSS, so if you were to implement a more robust solution that would definitely be something needed and welcomed!

**Comment by rriemann** [comment]
To answer your last question on http://ruhoh.com/usage/plugins/#toc_5

> I'm thinking about adding this as a default task, but I'm hesitant to require the additional nokogiri dependency -- what do you think?

Of course there is a need for rss of each blogging system!

**Comment by plusjade** [comment]
RSS will be officially added into the gem =)

**Comment by plusjade** [comment]
RSS generator officially added to gem in [ruhoh v.1.0.0.alpha](http://ruhoh.com/blog/releases/version-1-0-0-alpha/).
