### ISSUE TITLE
2.0.alpha.3 throws runtime error on pages not in the root page directory

### ISSUE THREAD

**Issue by binaryphile** [ruhoh/ruhoh.rb#149]
I have a working instance, but when I make a page like pages/test/test.md, I get the following error in development:

```
RuntimeError at /test/test
Page id not found for url: /test/test

Ruby    /home/ted/.rvm/gems/ruby-1.9.3-p385/bundler/gems/ruhoh.rb-2dda1004eca2/lib/ruhoh/resources/_page/previewer.rb: in call, line 16
Web GET fides.binaryphile.com/test/test
```

Works fine in ruhoh 1.1.

**Comment by plusjade** [comment]
Can you paste your config.yml file? 2.0.rc makes even more changes (sigh hopefully this weekend will be the miracle weekend I release it) so I'm getting quite out of sync with all the multiple iterations between versions.

Suffice to say it may just be an improper configuration in config.yml but I'll have to run it locally to verify. Thanks!

**Comment by binaryphile** [comment]
Thanks!  You can see it here: https://github.com/binaryphile/tampawomanshealth/blob/develop/config.yml

In fact you can see my whole site there, although I haven't checked in the theme yet (nor the test page).  You'll need to switch the theme back to twitter probably.

**Comment by binaryphile** [comment]
Funny, just tried it again (after going through the trouble to migrate back to 1.1) and 2.0 seems to be working with the page in the subdirectory.  I probably just screwed something up.  I'll leave this open for a bit while I investigate further.

**Comment by plusjade** [comment]
Yeah if i switch the theme to 'twitter' it's working in that I can find the pages in the pages directory but other things are breaking, primarily the mustache stuff. Let me know if you get anywhere with it, I'd really like to bump everything to 2.0.rc this weekend so even though it won't be a complete launch, it will be much better to concentrate attention on a stable API, because I'm pretty out of sync with even 2.0.alpha.3 at this moment =/

Wish me luck and really, I appreciate the patience. It's cool that you're using ruhoh for some static sites like the one you referenced =) so I have some new motivation to get the rc finalized.

**Comment by binaryphile** [comment]
I'm sure this was something wrong with my configuration.  Haven't had any problems like it for a while.
