### ISSUE TITLE
invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by tlupfer** [ruhoh/ruhoh.rb#150]
I get this error with the latest code and ruby-2.0.0-p195.

timimac:www.slowtheory.com timlupfer$ bundle exec rackup
/usr/local/rvm/gems/ruby-2.0.0-p195/bundler/gems/ruhoh.rb-9fe5d7cdf5e7/lib/ruhoh/base/model.rb:102:in `match': invalid byte sequence in UTF-8 (ArgumentError)

**Comment by plusjade** [comment]
@tlupfer I recently pushed months of work into the master branch so I'm not sure if you are using that latest code (2.1) or if you are in 2.0.alpha.x  -- Even I am very confused myself so I want to release 2.1 asap, I just have one final issue to resolve before I can do that (pagination is not working correctly unfortunately).

So if you can tell me what codebase you are on , I can run it and check out the error.
Also if you your blog is public, I can run your blog and see what is causing the error.
It very well may just be a ruby 2 compatibility issue as I have not tested ruhoh with ruby 2.0.
Lastly it also may just be strange characters in your blog that is causing yaml and/or markdown processing to break (I honestly am not very knowledgable how to compensate for the various encoding scenarios and support)

**Comment by tlupfer** [comment]
It's dying on "/Users/timlupfer/Git/ruhoh/www.slowtheory.com/themes/simple/fonts/glyphicons-regular.eot" which probably makes sense, but I'm guessing it shouldn't be trying to do anything at all with that file? Version information:

timimac:www.slowtheory.com timlupfer$ head -n5 Gemfile.lock 
GIT
  remote: git://github.com/ruhoh/ruhoh.rb.git
  revision: 9fe5d7cdf5e79a37f2dcdd612bae4f2cf0c67435
  specs:
    ruhoh (2.0.alpha.3)

I'll check out the master branch.

blog is http://www.slowtheory.com/blog

**Comment by tlupfer** [comment]
Same thing specifying master branch. Removing the fonts and media directories allows rack to start without dying (other issues occur then, but I'll keep this thread on topic). 

The issue seems to be trying to parse everything in the themes directory as a page.

**Comment by plusjade** [comment]
Ah I think the problem is the new config format.

Themes are now optional and no longer name-spaced into the theme folder. "Every folder is a collection" so if you want a folder to behave like a theme you just put the theme folder directly into the root of your blog and define which collection processor to use in the config:

``` yaml
# config.yml

"twitter-theme" :
    "use" : "theme"

"posts" :
    permalink: "/blah"
```

So basically you are telling the folder "twitter-theme" to use "theme" to model itself. By default all collections default to  "pages", which allows you to define a folder "essays" which will automatically be modeled as the "essays" collection.  It works like "posts" did in 2.1 e.g:

```
{{# essays.all }}
   {{ title }}
{{/ essays.all }}
```

And of course there are "special" collections like `layouts`, `partials`, `javascripts` which default to those collection names since they are special (if named appropriately).

I have the new documentation ready to go in [ruhoh.com](https://github.com/ruhoh/ruhoh.com) branch but still have one last issue to fix.

Hopefully that makes some sense.

**Comment by tlupfer** [comment]
Issue solved by making required configuration changes for 2.1.
