### ISSUE TITLE
still outputs paginated links when config.yml.paginator.enable == false

### ISSUE THREAD

**Issue by coolaj86** [ruhoh/ruhoh.rb#185]
The button links for pages [1], [2], [3], etc are still at the bottom of the page even when pagination is disabled.

**Comment by plusjade** [comment]
Are you referring to the initial home page? If so this is related to #183 in that the homepage is just a manual implementation of what is on the paginator.html page. In other words, because it is manually added, the system doesn't know to omit it when disabling the paginator. Solving #183 should therefore also solve this issue.

**Comment by plusjade** [comment]
Closing in favor of addressing #183
