### ISSUE TITLE
Is it possible to get at the contents of a specific page from within a layout?

### ISSUE THREAD

**Issue by webmasterkai** [ruhoh/ruhoh.rb#204]
In trying to create a one page design what would be the best way to include data/content from specific files?

Let's say we just have a simple site with 3 markdown files such as "about", "services", "work". Is there a way to includes those specific files throughout the layout file? Something such as {{pages.by_name.about}} or maybe {{pages.by_name.about?to_page}}

Is there a way to print out a textual representation of the database object?

Thanks!

**Comment by plusjade** [comment]
@webmasterkai good idea. I managed to mock up a working plugin:

``` ruby
## my-blog/plugins/pages_find_by_name.rb

module PagesFindByName
  def find_by_name
    @find_by_name ||= FindByNameProxy.new(self)
  end

  class FindByNameProxy < SimpleDelegator
    def method_missing(name, *args, &block)
      model = __getobj__.find(name.to_s)
      model ? model : super
    end

    def respond_to?(method)
      __getobj__.find(method.to_s) ? true : super
    end
  end
end

Ruhoh::Resources::Pages::CollectionView.send(:include, PagesFindByName)
```

The above plugin exposes `pages.find_by_name` method which in turn proxies to the `FindByNameProxy` class instance. This allows us to respond to method calls on our method, e.g. `pages.find_by_name.some-method`. Note the valid use of a hyphen there since this call is processed by mustache.

Now in your view:

``` html
# my-blog/_root/index.html

{{# pages.find_by_name.about-me }}

  <h4>{{ title }}</h4>

  {{{ summary }}}

{{/ pages.find_by_name.about-me }}
```

This assumes you have a valid file at `my-blog/pages/about-me.md`

---

I should consider putting this into the core if people want this.

> Is there a way to print out a textual representation of the database object?

The above example exposes the model_view class instance which gives you access to everything you need that is an attribute of that data resource. Was there something else you need? The original question seems to imply you want to include sub-layouts into other layouts. Can you use includes for this?

**Comment by webmasterkai** [comment]
@plusjade You are my f'ing hero!

**Comment by bjornmeansbear** [comment]
This is great. As long as a sub-layout would still work for bits of the content, then this seems exactly like something I was trying to do, but hacked together by tagging everything and just calling individual tags for each area.

**Comment by plusjade** [comment]
Glad it works for you =)

**Comment by waynedpj** [comment]
i was wondering if it would be possible to extend this plugin to use a data variable (e.g. from front matter) for finding a page in a collection by name, instead of a hard coded value.  for example, with the following 2 top level collections:

```
albums/
  album-01/
    index.html
  album-02/
    index.html
tracks/
  track-01/
    index.html
  track-02/
    index.html
  track-03/
    index.html
  track-04/
    index.html
  track-05/
    index.html
  track-06/
    index.html
```

we could use the following for album-01 to pull in particular tracks, though without defining a separate Mustache tag for each one:

```
---
album-tracks:
  - track-01
  - track-04
  - track-05
  - track-06
---
# my-blog/albums/album-01/index.html
{{# album-tracks }}
  {{# tracks.find_by_name.{{ . }} }}
    <h4>{{ title }}</h4>
    {{{ summary }}}
  {{/ tracks.find_by_name.{{ . }}
{{/album-tracks}}
```

i have tried variations on this but so far it seems like a Mustache tag cannot be embedded within another one.  i believe a Mustache block helper could work at this with rendering the embedded tag first and will see what i can come up with.

thanks
