### ISSUE TITLE
kramdown is not installed with ruhoh

### ISSUE THREAD

**Issue by rlemon** [ruhoh/ruhoh.rb#24]
The documentation says `maruku` is used for markdown parsing but the newest version uses kramdown. However the GEM file still installs maruku.  Please update the GEM file to install the correct dependencies..  also http://ruhoh.com/usage/ is horribly out of date. broken links and wrong information.

**Comment by plusjade** [comment]
Thanks, for some reason it's expecting kramdown. I know I'm working on this in my dev branches but seriously cannot find where its called in the master branch!?

Quick fix would be to install kramdown just to get it running:

``` bash
$ gem install kramdown
```

I should push out 0.2.2 soon and try to fix this.

**Comment by plusjade** [comment]
I've switched to redcarpet in version 0.3.0. This issue should be resolved by upgrading:

``` bash
$ gem install ruhoh --version '0.3.0'
```

Notes for v0.3.0 release: http://ruhoh.com/blog/releases/version-030/

**Comment by rlemon** [comment]
Cool, I installed kramdown before I posted the issue so i'm good for using this. however i did think it would be nice for you to know :P thanks. keep up the good work! (PHP or Python port any time soon?)

**Comment by plusjade** [comment]
I want/need to get the API stabilized in order to start porting. One of my goals is to be able to port this already because that means I'd have an excuse and a project to learn more languages. However it's already a bit difficult to iterate fast because I have to make sure to properly version, document, and not break anything too bad. So I'd imagine multiple projects in different languages would just make that exponentially harder.

Long story short, once we settle in on a v1.0.0 that is stable _enough_ we'll finally get to explore some other languages. I'd prefer python , but PHP is really important because it's an easy language to setup.

I think my last major breaking change will be to rename all the directories to not user an underscore it's not necessary anymore, all the files are "opt in" so to speak. And I'm not too find of my _template folder structure. Seems convoluted so I'll probably simplify that. If that sounds good to you I'd be more inclined to do it!

thanks for the feedback, it's really helpful.

**Comment by rlemon** [comment]
TBH i'm still just 'playing' with it trying to figure out how you have this all working (I don't know Ruby so it's an adventure). Python would obvious first choice for another port (PHP is fast and easy, but only because of the MASSIVE amount of community resources IMO). Python just seems like something a bit more in tuned to generating a static site (don't ask me why, I just think that :P ). 

now with that said, I know PHP and not Python (well enough) , once you get the PHP port going i'd be more than glad to lend a hand.

**Comment by plusjade** [comment]
cool that's definitely what I need! I started with PHP so I know the syntax and language, but I'm far too removed from it now to do anything efficient. Some insight into current practices and libraries would definitely help me. I'll be pinging you when the time comes!
