### ISSUE TITLE
List multiple posts on the same view.

### ISSUE THREAD

**Issue by rlemon** [ruhoh/ruhoh.rb#32]
I'm sorry if this is not really the medium for this question; however I have been playing with the API and i'm trying to list multiple posts or pages (layouts) on the same view... 

Like, how (if possible) to move the entire layout for a post or page into a partial. Does this require some finagling with the rb source? or can this be achieved with a helper? Sorry I don't really know to much about Ruby or mustache. Kinda running at this blind.

**Comment by plusjade** [comment]
@rlemon when you say:

> list multiple posts or pages (layouts) on the same view...

Can you give me a more concrete example? Are you trying to implement a kind of "blog index page" where it lists the latest n number of posts then displays either a summary with link to "more" or the entire post content itself?

> Like, how (if possible) to move the entire layout for a post or page into a partial.

Ideally you should be able to this by simply copy and paste, but I realize now that all layouts make use of the special variable: `{{ content }}` to render the page content. I say special because this is _not_ actually parsed by mustache, rather just a regular expression -- which in retrospect, is dumb. The point being if you put your layout into a partial and then called the partial, everything will work normally (because partials just get expanded into their parent container) _except_ the special `{{content}}` token because the conten token is processed _before_ any mustache rendering takes place.

I will plan on re-implementing this functionality to make it more intuitive.

You can help me by giving me your specific use-case. What do you want to achieve and what syntax are you trying to use to achieve it. it's okay if it doesn't work at all, it's mainly so I can try to understand and come up with a way to do it within the system.

Thanks!

**Comment by dph01** [comment]
Hi  - I have the same requirement (if I understand rlemon's question correctly).

I'm looking to migrate my current blog from Posterous (http://tech.damianhelme.com). I'm trying to recreate in Ruhoh my Posterous home page that shows the complete text for the last n posts. Each post has a click through to go to the comments section. Well, Posterous actually expands the comments inline, but I'd be happy (at least for the time being, possibly a future feature request?) to click through to the separate page for that post that contains the comments section etc.

Like rlemon, I don't know Ruby or Mustache, and can't really get off the starting blocks.

**Comment by plusjade** [comment]
@dph01 I currently have this feature working in my [development branch](https://github.com/ruhoh/ruhoh.rb/tree/0.4.0)
The new release is still about a week away since I have to add tests and documentation and there are many breaking changes as well. I'll get some docs up on how to run the current version in development for those interested.

Until then you can look forward to the logical way to accomplish this:

``` html
{{# posts }}
  <h3>{{title}}</h3>  
  {{{content}}}
{{/ posts }}
```

With limits:

``` html
{{# posts_limit_5 }}
  <h3>{{title}}</h3>  
  {{{content}}}
{{/ posts_limit_5 }}
```

You'll notice the **triple** mustache syntax for `{{{content}}}`. This is needed to avoid escaping HTML characters that exist in the content body.

Quick question, since @rlemon and @dph01 are both new to mustache, how is this style of templating treating you?  The main idea behind mustache is "no logic in the templates". This lends itself particularly well to supporting a universal standardized API, but it can also be a little unintuitive for users used to traditional inline templating syntax -- what are your thoughts so far?

**Comment by dph01** [comment]
great - looking forward to the release!

> how is this style of templating treating you?

seems fine so far. Not really had to do much other than understand the default templates/layouts etc and all seems pretty clear. I'll give you more feedback if things change as I get my hands dirtier.

**Comment by lynnfaraday** [comment]
@plusjade - Thanks for implementing this.   To answer your question since I am also new to mustache: I found the examples on your page very easy, but extending it to add new template items in plugins was pretty confusing - especially the "_limit_5" type of syntax of passing arguments.  But now that I understand it, it seems pretty cool.

**Comment by plusjade** [comment]
@lynnfaraday - since you mentioned you were new to ruby, just to be clear the `posts_limit_5` syntax is a hack that relies on the `method_missing` call. In other words it's not a standard way to do something in ruby, rather it's working in the constraints of how mustache works. In mustache there is no concept of argument passing, so we have to hack the method call to include the arguments in the method itself.

**Comment by lynnfaraday** [comment]
@plusjade - Good to know, thanks!   Though since you mentioned wanting to support a whole bunch of languages in the API, will this be extensible to them?   Is there some other template language that supports arguments more readily?

**Comment by plusjade** [comment]
@lynnfaraday mustache was choosen for ruhoh because it has already been implemented in a variety of other languages: http://mustache.github.com/.  Traditionally, the most popular templating languages are nothing more than embedded code. Think PHP where your documents can jump in and out of PHP as needed. The reasoning behind mustache is to completely do away with this kind of templating; reason being is that it tends to get unmaintainable eventually and is the definition of spaghetti code. Specifically for ruhoh, embedded code would be impossible to support because there would/could not be a standardized API to build a theme and functionality on top of.

Mustache takes a bit of getting used to but I do think it offers a superior user experience over time.

**Comment by lynnfaraday** [comment]
@plusjade - Fair enough.  I guess I'm just biased since the two extensions I've tried to make so far have both required arguments :)   It does seem like a nice language apart from that.

**Comment by alxjrvs** [comment]
@plusjade the "{{{ content }}}" escape may be something you want to include in documentation - I just had written something similar to this ( forgive me if I get a small piece of syntax wrong, the idea is that I am iterating over a block):

 {{ # posts }}
  {{ title }}
  {{ content }} 
 {{ / posts }} 

Which, as I learned, spits out the unescaped html. the {{{ content }}} escape works fine, but I had to dig for it.

**Comment by plusjade** [comment]
@alxjrvs thanks for documenting this, you are definitely right. The new version makes extensive use of the triple mustache tags just because a lot more functionality is going through mustache now. I'll make sure to clearly include this in the docs. BTW did you hack out the `{{{ content }}}` functionality yourself, or are you using/referencing the [0.4.0 development branch](https://github.com/ruhoh/ruhoh.rb/tree/0.4.0)?

**Comment by alxjrvs** [comment]
@plusjade I don't believe that I am using the development branch, but it definitely is working on my end. Compare the homepage of [alxjrvs.ruhoh.com](http://alxjrvs.ruhoh.com/) to [my index page](https://github.com/alxjrvs/alxjrvs.ruhoh.com/blob/master/_pages/index.html).

**Comment by plusjade** [comment]
@alxjrvs ah good to know. I was initially very puzzled by how it was working since I hadn't designed it for that use case. It turns out that due to ruby's mutable objects (that is you can mutate an object at any time) if every post/page object has its "content" rendered, the rendered content will persist in the database. 

For obvious reasons we don't want to depend on having previously rendered the content in order for the content to be accessible, so the new version lazy-loads in a page/post's content anytime the system asks for it, even in other pages and in loops of course.

The new version works with the exact same syntax you're using so you're all set. Additionally you will be able to do `{{{ summary }}}` to output the first n lines of your posts, so stay tuned for that.

**Comment by alxjrvs** [comment]
@plusjade great to hear. Looking forward to it.

**Comment by plusjade** [comment]
Page content [accessor](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/page.rb#L77-80) and [mustache helper](https://github.com/ruhoh/ruhoh.rb/blob/master/lib/ruhoh/templaters/rmustache.rb#L36-40) added in [ruhoh v.1.0.0.alpha](http://ruhoh.com/blog/releases/version-1-0-0-alpha/).

Your specific use case is documented here: [posts_latest index](https://github.com/ruhoh/blog/blob/master/pages/index.html#L16-26) Let me know how this works for you guys!

See [Configure documentation](http://ruhoh.com/usage/configure/) for configuring posts_latest and summary helpers.

**Note:** Feel free to open new feature-specific issues related to the new posts_latest, summary, and index features. e.g. iterate over specific category, tag, year, or pagination etc.

**Comment by dph01** [comment]
fantastic - thanks for that, looks to be working well!

I see you've marked it as an 'alpha' release. Is there anything you know of that would prevent me from putting my site live with this version?

Thanks again

Damian

**Comment by plusjade** [comment]
@dph01 I consider the release production ready. The reason I marked it alpha is just because I want to vet the major features and additions. I don't have a lot of test coverage so there might be some bugs etc that I wasn't able to catch.

Overall I consider 1.0.0 a significant milestone so just wanted to take a while to do some due diligence _in the wild_. But the fact that it's still 1.0.x.x means that the API will be much much more stable and backwards compatible than the previous 0.x.x versions.

**Comment by dph01** [comment]
great thanks. It seems to be working well for me.

On Fri, Jun 8, 2012 at 7:11 AM, Jade <
reply@reply.github.com

**Comment by rlemon** [comment]
Sorry Diablo 3... been busy... :P I'll look into the changes you've made and comment :P
