### ISSUE TITLE
URL Reserved Characted in Page Titles Causes Errors

### ISSUE THREAD

**Issue by davejlong** [ruhoh/ruhoh.rb#36]
If you have URL reserved characters like the question mark (?) in the title of a post, an error is generated by most browsers when you push the compiled site to a server. Running `ruhoh titleize` gives proper titles for the files, but `ruhoh compile` builds poor URLs.

An example can be found at http://davejlong.ruhoh.com in the "IDE or Text Editor?" post.

**Comment by plusjade** [comment]
@davejlong: Ah yes, the url generation is turning out to be quite problematic. Other users have expressed frustration with not being able to cleanly import WordPress and other blog software posts because of the differences in URL formats.

I haphazardly ported over Jekyl's URL formatting logic but I see now that we want to make the URL module as extensible as possible to allow for truly fine grained tuning.  

I expect to push some improvements in the next few days with my new release. Thanks for reporting this!

**Comment by plusjade** [comment]
@davejlong this should be fixed in [ruhoh v.1.0.0.alpha](http://ruhoh.com/blog/releases/version-1-0-0-alpha/). Rather than CGI escaping special characters we are omitting them. Let me know how it goes. Closes same issue #40
