### ISSUE TITLE
Ignore *~ temporary files when scanning for posts in _posts/

### ISSUE THREAD

**Issue by jfinkels** [ruhoh/ruhoh.rb#37]

**Comment by plusjade** [comment]
@jfinkels: This is currently supported via the `exclude` parameter in `_config.yml`.  You can define a string that will get converted to a regular expression via `Regexp.new(str)`:

``` yaml
#_config.yml

exclude: '~$'
```

Here your string will get converted to `/~$/` via `Regexp.new(str)`. You can also optionally pass more than one regex via array.

One thing to note is that all posts filenames actually begin with `_posts/`. So if you want to match the start of any post files you have to do it like this:

``` yaml
#_config.yml

exclude: '^_posts/~'
```

**NOTE**: In the new version 0.4.0, the new config syntax will be namespaced into a posts hash:

``` yaml
#config.yml

posts:
  exclude: '^_posts/~'

pages:
  exclude: '~$'
```

**Comment by jfinkels** [comment]
Is this in the documentation on http://ruhoh.com? I couldn't find it.

**Comment by plusjade** [comment]
@jfinkels no it is not =x. I push out features faster than I can document them. I have even omitted inline code documentation because the code changes too much.

Rest assured this haphazardness should only be temporary, once I get the API stabilized I'm going to spend a lot more time documenting everything properly so more people can help contribute and peer review.

P.S. This _is_ documented in the v0.4.0 docs which I am just finishing now, hopefully I can push today.

**Comment by jfinkels** [comment]
I understand. Keep up the good work!

**Comment by plusjade** [comment]
[Post and page exclude settings now officially documented](http://ruhoh.com/usage/configure/) This works in [ruhoh v.1.0.0.alpha](http://ruhoh.com/blog/releases/version-1-0-0-alpha/).
