### ISSUE TITLE
Post (and other) urls without trailing slashes?

### ISSUE THREAD

**Issue by jergason** [ruhoh/ruhoh.rb#45]
Is there a way to generate posts without trailing slashes? Right now each post seems to compile down to a directory containing an index.html file.

I changed the posts permalink in the `config.yml` file to remove the trailing slash and it now looks like this:

``` yaml
posts:
  permalink: /:categories/:title
```

I created a post with `ruhoh post durp`.

However, when I run `ruhoh compile`, the `compiled` directory structure looks like this:

``` bash
compiled/
├── about
│   └── index.html
├── archive
│   └── index.html
├── assets
│   ├── media
│   └── twitter
│       ├── media
│       │   ├── glyphicons-halflings-white.png
│       │   └── glyphicons-halflings.png
│       ├── stylesheets
│       │   ├── bootstrap.min.css
│       │   └── style.css
│       └── widgets
│           └── google_prettify
│               └── stylesheets
│                   └── twitter-bootstrap.css
├── categories
│   └── index.html
├── durp
│   └── index.html
├── index.html
├── pages
│   └── index.html
├── rss.xml
└── tags
    └── index.html
```

This means the url for my post is `durp/`, with the trailing slash. Is there a way to generate posts and other pages without putting them all in separate directories so their urls don't have trailing slashes?

**Comment by jergason** [comment]
After looking through the code, it seems like the `Page#compiled_path` method defaults to adding an `index.html` to the end of the path if it doesn't end in a `.whatever`:

``` Ruby

    def compiled_path
      self.ensure_id
      path = CGI.unescape(@data['url']).gsub(/^\//, '') #strip leading slash.
      path = "index.html" if path.empty?
      path += '/index.html' unless path =~ /\.\w+$/
      path
    end
```

This is not the behavior I would expect, and seems like something I would want to optionally turn on in configuration. Is there a reason for this behavior? If not, I will work on a pull request to make it configurable.

**Comment by jergason** [comment]
So it looks like the browser tries to download files if they don't end with `.html`. Any ideas on how to solve this?

**Comment by plusjade** [comment]
> This means the url for my post is durp/, with the trailing slash. Is there a way to generate posts and other pages without putting them all in separate directories so their urls don't have trailing slashes?

@jergason I'll take a more in depth look at this later today but at first glance I'm pretty sure this falls under the web-server functionality. In order to use those "clean" urls a static web server needs to serve the root index file of the directory. I'm assuming trailing slashes are required to denote the path as a path to a directory.

To not serve from a directory you can alternatively specify the extension:

```
posts:
permalink: /:categories/:title.html
```

I'm using nginx to serve all *.ruhoh.com websites and you can see here that I can give you the link without a trailing slash:
http://ruhoh.com/usage  and nginx will correctly handle the link. Though if you look up at the url bar you will not the trailing slash has been added.

> This is not the behavior I would expect, and seems like something I would want to optionally turn on in configuration. Is there a reason for this behavior? If not, I will work on a pull request to make it configurable.

The intended usage is a litle tricky here.  So the idea is that all page objects being modeled by the Page class will already have properly processed/formated URL at `@data['url']`. Since we are serving static files then it makes sense that every page _has to be a file_. For pages that have explicitly set their extension (sitemap.txt, rss.xml, etc) we'll go ahead and use that file extension. However for pages that do not have a file extension set, we are _assuming_ that the URL is "pretty" and the only way to get that functionality, statically (save for messing with the web server config which is beyond the scope of ruhoh) is to save serve an index.html from a directory.  

> So it looks like the browser tries to download files if they don't end with .html. Any ideas on how to solve this?

You are definitely right about this one, I just made a test post and indeed the browser tries to download the file: http://ruhoh.com/data.json . I'm pretty sure this is a web-server configuration issue. I'll play around with it today and see if I can get it working and report back.

Can you tell me a little more about your use-case? Let me know if we are on the same page as far as expected functionality. Also, if you don't mind publicly hosting your blog online, it will allow me to clone it and play with the code to help get the features you need.

**Comment by jergason** [comment]
Here is [my blog](https://github.com/jergason/blog.git) in a proto-state, still in the midst of a transfer out of Tumblr. It sounds like you are right, that it is a server configuration issue, but maybe there is some workaround.

**Comment by plusjade** [comment]
Closing issue with the conclusion that this falls under a the web server's responsibility. We can address fine-tuning these sorts of things at a later time if need be.
