### ISSUE TITLE
Livefyre widget doesn't work

### ISSUE THREAD

**Issue by aussetg** [ruhoh/ruhoh.rb#50]
Using Livefyre doesn't work.

2 problems :
Ruho doesn't seem to include the site_name in the source code.
( Disqus , which work uses the  {{ config.disqus.short_name }} syntax while livefyre uses {{ config.comments.livefyre.site_id }}  )

Even then when manually entering the site_id in the code Livefyre doesn't load.

**Comment by plusjade** [comment]
@Darknight670, this bug is confirmed. This bug also affects all the other comment widgets except for disqus. I will fix this in the next release.

In the meantime you can get this to work by _overloading_ the system level livefyre layout. 

In your blog you should have a widgets folder:

```
- widgets
  - comments
    - config.yml
    - layouts
      - livefyre.html ←
```

Then in the livefyre.html file place the corrected code:

``` html
<script type='text/javascript' src='http://zor.livefyre.com/wjs/v1.0/javascripts/livefyre_init.js'></script>
<script type='text/javascript'>
    var fyre = LF({
        site_id: {{ config.livefyre.site_id }}
    });
</script>
```

**Comment by plusjade** [comment]
Fix: https://github.com/ruhoh/ruhoh.rb/commit/331eff36d8355c0113ca39b4e70eaf93a3cfaaa4
