### ISSUE TITLE
production_url has no affect

### ISSUE THREAD

**Issue by okigan** [ruhoh/ruhoh.rb#56]
Updates to production_url do not seem to have an effect -- link in navigation bar still point to <username>.ruhoh.com.

**Comment by okigan** [comment]
here a repro with ruhoh.com itself (!?): https://github.com/ruhoh/ruhoh.com/blob/master/config.yml

**Comment by okigan** [comment]
issue also identified here:
https://github.com/ruhoh/ruhoh.rb/pull/48

possibly address by this pull request:
https://github.com/celadevra/ruhoh.rb/commit/b0d54bf07d7a69145b2ddd899a77d7390e958f9f

**Comment by plusjade** [comment]
@okigan the production_url is technically only used for when you need an absolute link to your blog. The current (and only) use case is when generating the rss feed. 

The reason production_url does not act like a base path is because it's easiest to make the base-path relative: "/" 

The two main reasons I see for customizing the url is if you are serving your blog from a sub-directory (what @celadevra is working on) and/or if you intend to serve assets from a CDN, which is a planned feature but no yet implemented. Basically you would configure path_to_cdn, and all media-based assets are served from the cdn root.

Can you tell me your use case for needing to set a base path other than "/" ?

**Comment by plusjade** [comment]
Use base_path for name-spacing your blog into sub-directories: https://github.com/ruhoh/ruhoh.rb/issues/100
