### ISSUE TITLE
Support for JSON configuration

### ISSUE THREAD

**Issue by barkmadley** [ruhoh/ruhoh.rb#6]
How hard would it be to be able to use json in place of yaml in more places?

particularly in the front-matter and the _config files.

**Comment by plusjade** [comment]
Not hard, but what would be your primary reason?

Personally, I do lean toward using JSON for configuration files because json is handled more easily by more languages. But the main advantage of yaml is that it is "not a markup language" of course ;) . i.e. it's probably easier for beginners to use and understand at first glance?

I do think JSON would be a better technical implementation choice but I'm not too sure on the usability aspect just yet.
Looking forward to your opinion on the matter.

**Comment by barkmadley** [comment]
Just bike shedding.

I personally find yaml syntax awkward and non-intuitive at times (how do you nest a list inside a key-value object inside a list? I bet it looks ugly).
JSON has consistency on its side in my mind.

**Comment by plusjade** [comment]
Funny thing I learned during this project: JSON is valid YAML as long a the entire YAML document is JSON.

Example:

**File: theme.yml**

``` yaml
{
  "stylesheets" : {
    "default" : [
      "bootstrap.min.css",
      "style.css"
    ],

    "widgets" : {
      "google_prettify" : "twitter-bootstrap.css"
    }

  },

  "javascripts" : {
    "default" : [
    ]
  },

  "manifest" : {
    "author" : "Jacob Thornton and Mark Otto",
    "website" : "http://twitter.github.com/bootstrap"
  }
}
```

source: https://github.com/ruhoh/blog/blob/2.0.alpha/themes/twitter/theme.yml

Would be possible to allow a setting for working with .json and .yml files, but as you mentioned, not really a high priority.
