### ISSUE TITLE
Keep widget assets and config in one place

### ISSUE THREAD

**Issue by ramnathv** [ruhoh/ruhoh.rb#66]
I really like the widgets concept implemented in `ruhoh`. It facilitates plug and chug workflows. However, I find it a little strange that assets of widgets are split across directories. Case in point: `google_prettify`. The stylesheets are in the `theme/widgets` folder while the `javascripts` and `layouts` are in the `widgets` folder. Moreover, the configuration options are also split across two different files. 

So in essence, I can't get a widget working by just copying it to the widgets folder, and instead have to split the files across the `theme` and `widgets` folder. 

I think it would make for better design if all assets and default configuration options for a widget were kept in the same place. In order for themes to style the widgets, they can be allowed to overrule default settings. This would follow the same principle of cascading that you describe.

Let me know what you think.

**Comment by ramnathv** [comment]
It might additionally make sense to keep the widget and theme folder structures consistent. I would argue that themes are essentially a special kind of widget that style the overall look and layout of the blog/page. The theme/widget folder would have the following structure

```
javascripts
layouts
media
stylesheets
config.yml
```

**Comment by okigan** [comment]
check out https://github.com/ruhoh/ruhoh.rb/issues/63 which is similar in concept and targets project pages.

**Comment by plusjade** [comment]
@ramnathv I was wrestling with this a lot myself. It is very hard to design a modular system and have module components exist in two places!

My decision comes down down to the fact that I believe styling rules should be separate from function. 

##### Example

Suppose I make a widget that enables searching based on tags. The search is implemented in javascript and provides a basic UI consisting of a form input box and a bulleted list of tags from which to select from. The resultant data is also rendered using a bulleted list.

Here I have specified and implemented my widget functionality in javascript and I have defined the base UI as an HTML layout. It is very unlikely that any added _design_ elements I bundle into my widget are going to match _cleanly_ with a user's current theme and moreover their interpretation of how the UI should look and feel.

At this point I feel bundling styling rules is a _nice_to_have_ rather than an ideal design strategy. It's only convenient in the sense that a user will _not_care_ how something looks. However I really want to (ultimately) give a lot of power to designers and let them do what they are good at. Conversely widgets are made to **do stuff** so they should let developers do what they are good at without needing to ship haphazard styling rules.

I know at this point much that I am talking about is a gross over-engineering. However that's part of the fun of coming up with strategies, testing them out, getting feedback, and learning!

I just can't see a good case where bundling design rules with a widget is going to work out for the majority of users. I don't know much about design but I do know the design should be consistent. In this way, relative to the designer, ruhoh is actually _highly_ modular. The designer can overwrite and define everything he needs to style entirely in his theme.

---

I  do like your idea of everything cascading _from the theme_ though. I agree it would be better to have one central place for widget configuration. However we run into a scoping problem. If all widgets are configured via theme, then changing themes necessarily means duplicating configuration params across all themes. Currently widgets have self contained config params. In this way they are "global" and changing themes does not affect the widget config. However themes can override widget settings if they deem it necessary.

As you can see, there are plenty of scenarios for which we have to consider and design for. I definitely don't want to close this discussion. However the solution will have to encompass everything I've covered. Looking forward to your thoughts!

**Comment by lynnfaraday** [comment]
I thought about this too... my feeling was that it's OK to have it split.   Consider the case where there's a very popular widget that becomes 'mainstream' - each theme will probably want to style it in a different way, but there's no reason to duplicate the functional code.   Now consider the case where you're a widget designer distributing your own creation.  It's a little awkward, but it's not really that bad to bundle them up and have the user put things in two places.

**Comment by ramnathv** [comment]
I spent quite some time thinking through the comments made here and all the points are valid. My use case may not be typical, but let me explain with an example. Suppose, I want to start using a particular jquery tooltips plugin. It comes with its own set of stylesheets. Now, a natural workflow to me would be the following:
1. Copy the widget to the widgets folder.
2. Add a layout file indicating how it can be inserted into a page.
3. Modify a theme's configuration file to specify stylesheets to use.

Under the current setup, if I am to use default stylesheets that come with a widget, I need to copy it to every theme that I use, which is clearly not DRY. My instinct would be keep all default assets that come with a widget in one place so that reuse is DRY and easy and use the theme to configure settings. If a theme want's to style a widget by itself, that is fine too, but a lot of times, the widget is orthogonal to the page and hence most of us would prefer using the default stylesheets that come with it.

Once again, just my 2 cents. I know such design decisions involve a lot of factors.

**Comment by lynnfaraday** [comment]
@ramnathv -  I totally get what you're saying about DRY, but my question back would be:   What are the odds that the widget appearance will look exactly the same in each of your themes?   The few widgets I've been playing around with have been distinctly styled per-theme, so I've seen the advantages of keeping the style information separate.

It might be convenient for your case to have the widget come with a /default/ theme/stylesheet that you can override on a per-theme basis, but I'm not sure how practical that would be to implement.

**Comment by ramnathv** [comment]
I see your point. I guess the difference is due to the kind of widgets we encounter.
