### ISSUE TITLE
Support CSS/JS compilation and minification

### ISSUE THREAD

**Issue by tkellen** [ruhoh/ruhoh.rb#7]
This includes processing for languages like SASS, LESS, coffeescript etc. 

loving ruhoh so far!  just curious if there is any plan for adding this.

**Comment by plusjade** [comment]
Yes, I expect modules to be built to handle those. The principle design strategy of ruhoh is modularity so it will have to be a layer on top of how ruhoh currently works, rather than strictly built-in. 

Honestly this is a ways away for me to _personally_ work on though. Once I publish the docs on how to extent ruhoh I'd hope someone can take the lead in this area.

I have only worked with require.js for javascript packing. I think it is really nice but there is a non-trivial learning curve. 
As for for css LESS is quite possibly the easiest (as there is a javascript implementation) and Sass is straightforward as well.  Do you have any recommendations for js and css ?

**Comment by tkellen** [comment]
Seeing as how this is a ruby tool, I'd recommend checking out rake-pipeline and rake-pipeline-web-filters.  I think it would dovetail very nicely with your project.

**Comment by plusjade** [comment]
Sounds good, I'll give them a look and update this thread when I make any progress - thanks!

**Comment by plusjade** [comment]
Just to update this thread, we can probably start supporting minification at the compiler level using custom **compiler methods**.  which is new in version 0.3.0. See http://ruhoh.com/usage/plugins/ for compiler method documentation.

**Comment by pluskid** [comment]
Hoping to see this feature, too. Instead of using a compiler, maybe it's easier to use a custom converter. But it seems currently all Ruhoh converters only produce .html output. Hoping to see that the output extension/path of a converter could be customized.

**Comment by plusjade** [comment]
@pluskid Jekyll uses converters to process asset files much like you describe. The problem in ruhoh, however, is that converters are exclusively used for processing _content_ based files. Specifically that means all files in the "posts" and "pages" folders. 

In terms of assets: all assets should be packaged together with a theme so in order to run converters on the theme I'd need to specifically add in that functionality. However, to my understanding, asset management systems like [rake-pipeline](https://github.com/livingsocial/rake-pipeline) and [sprockets](https://github.com/sstephenson/sprockets) already have the converters built into them along with the DSL to run those conversions. 

Assuming this correct, I'd prefer to defer asset management over to one of these projects.

**Comment by pluskid** [comment]
@plusjade thanks for your references. I have other similar tasks like SASS. For example, I have .dot files I would like to convert to .png files and .asy files convert to .svg files, etc. I think I should definitely look at rake-pipeline.

**Comment by pluskid** [comment]
@plusjade now I used rake-pipeline to generate some contents into _compiled directory. But it seems those files are not available in the dev-mode rack server. Is there any way to enable viewing those files in local dev-mode server? Thanks!

Sorry for bothering, I figured it out with Rack::Static middleware (new to Rack). :p

**Comment by Meroje** [comment]
Could you please explain how you solved adding custom generated files to the rack mode ?

**Comment by pluskid** [comment]
@Meroje,
by using Rack::Static, add this (change for your own situation) to config.ru

```
use Rack::Static, :urls => ["/files/", "/rss.xml"], :root => "compiled"
```

**Comment by Meroje** [comment]
So no on the fly compilation for these files ?

**Comment by pluskid** [comment]
@Meroje,
I do not need to modify those files frequently, so I use rake to compile them manually. I also added a compiler-task plugin to execute rake, so then re-compiling the site, they will be automatically compiled.

**Comment by Meroje** [comment]
At least I can check these files locally, thank you !

**Comment by jackcallister** [comment]
@pluskid,
I'm curious about your SASS compilation set up. I've got SASS compilation working by directly editing the config.ru file but I'd rather a compiler-task plugin - is that what you've done? I'm not quite sure how to go about this, could you point me in the right direction.

**Comment by pluskid** [comment]
@jarsbe I was using rake-pipeline, and you just hand-craft anything you want to compile, and register it as a ruhoh compiler task. It will then be executed every time you run ruhoh.

**Comment by plusjade** [comment]
Ended up going with [sprockets](https://github.com/sstephenson/sprockets) because it's defacto standard for the ruby community. 

[Asset-pipeline documentation for ruhoh 2.1](http://ruhoh.com/docs/2/asset-pipeline/)
