### ISSUE TITLE
Incremental Compile?

### ISSUE THREAD

**Issue by lynnfaraday** [ruhoh/ruhoh.rb#75]
Having imported a lot of entries from my old blog, a full compile and upload takes _just_ long enough to be a frustrating.  I'm still fiddling around with rsync, which may help some, but I'm wondering if anyone else thinks that it would be valuable to have some sort of incremental compile option.  

As a first step, I think that it would let you specify just one post to compile (typically a new post).

The only trouble is that if you add a post, you'll also need to update the index/tags/archive/etc. pages.   I'm not sure how to do that in a modular manner since different folks will have different pages affected by a new post.   Should there be a config option for 'which pages to update on an incremental compile'?   Should it just automatically update all the regular pages and not all the posts?   Open to suggestions here.

**Comment by plusjade** [comment]
Single page/post compile is officially supported in [ruhoh 2.0](https://github.com/ruhoh/ruhoh.rb/tree/2.0.alpha). You can see the rough implementation outline in the [db.rb](https://github.com/ruhoh/ruhoh.rb/blob/2.0.alpha/lib/ruhoh/db.rb) file. 

In a nutshell ruhoh 2.0 lazy-loads everything. There is no longer any need to manually update the database. In this way we get dependency resolution for free. That is to say, for any file that calls (depends) on other data endpoints, the call itself will trigger the update/resolution. And of course if the data is already loaded, it is cached and used for subsequent calls.

Next ruhoh introduces a "pointer" system. All files are identified by a "pointer" which is a hash of filepath, relative name, and registered parser. This data uniquely identifies every file in your blog. What this means is you can request a singular resource from the database by referencing its pointer. The database will load the resource and resolve all of its dependencies. 

Here we have enabled single page/post compile but do note that for pages which loop through posts/pages (for example menus), this defines an implicit dependency on _requiring the existence of the post/page dictionary_ in order to loop through them! In this case multiple pages/posts will still be processed but it is overall a much more efficient system.
